#!/usr/bin/env python3
"""Generate the agent-mode gitconfig from the user's global config.

Agent-mode git authenticates ONLY as omp-harness[bot] on github.com. The
user's stored credentials are never visible to an agent, so every
`credential.*` key from the user's config is dropped, and every `include*`
key too (an include could reintroduce a helper). Everything else —
http.proxy, sslCAInfo, url.*.insteadOf, aliases, init.defaultBranch,
core.* — is preserved.

Uses `git config --global --list` (git's own parser: handles case
insensitivity, CRLF, and expands includes), then writes each surviving
key back with `git config --file`, so section/subsection reconstruction is
git's job, not ours. Finally registers the bot credential helper GENERICALLY
so every credential lookup routes through it: github.com mints a token, any
other host fails loudly with a helpful message.

Usage: gen-agent-gitconfig.py <out-file> <bot-helper-path>
"""

import os
import subprocess
import sys


def main() -> int:
    expected_args = 3  # program, out-file, bot-helper-path
    if len(sys.argv) != expected_args:
        print("usage: gen-agent-gitconfig.py <out-file> <bot-helper-path>", file=sys.stderr)
        return 2
    out, helper = sys.argv[1], sys.argv[2]

    settings: list[tuple[str, str]] = []
    # Read the USER's global config, never the agent config: when this runs
    # inside agent context the shim exports GIT_CONFIG_GLOBAL/GIT_CONFIG_NOSYSTEM,
    # which would make the regeneration derive from itself.
    env = dict(os.environ)
    env.pop("GIT_CONFIG_GLOBAL", None)
    env.pop("GIT_CONFIG_NOSYSTEM", None)
    r = subprocess.run(
        ["git", "config", "--global", "--null", "--list"],
        capture_output=True,
        text=True,
        env=env,
    )
    if r.returncode == 0 and r.stdout:
        # --null --list emits pairs as key\nvalue\0. credential.* is dropped
        # (agents see no user credentials), include* too (an include could
        # reintroduce a helper), and url.* (insteadOf rules rewrite
        # github.com URLs to SSH or other hosts, bypassing the helper).
        for pair in r.stdout.split("\0"):
            if not pair or "\n" not in pair:
                continue
            key, value = pair.split("\n", 1)
            if (key.startswith("credential.")
                    or key.startswith("include")
                    or key.startswith("url.")):
                continue
            settings.append((key, value))

    with open(out, "w") as f:
        f.write("# Agent-mode gitconfig, generated by omp-config "
                "tools/gen-agent-gitconfig.py\n")
        f.write("# Agents authenticate ONLY as omp-harness[bot] on github.com; "
                "the user's credentials are not visible.\n\n")
    for key, value in settings:
        subprocess.run(["git", "config", "--file", out, key, value], check=True)
    subprocess.run(["git", "config", "--file", out, "credential.helper", helper], check=True)

    print(f"wrote {out}: {len(settings)} preserved settings + bot credential helper")
    return 0


if __name__ == "__main__":
    sys.exit(main())
